!
hostname core
!
description Location: pb2
!
interface Loopback0
 description Router-ID
 ip address 10.2.3.1 255.255.255.255
!
interface Management0
 description Out-of-Band Management
 ip address 10.2.4.3 255.255.255.0
 no shutdown
!
end